# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FireBase_Demo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'

  # Pods for FireBase_Demo

  target 'FireBase_DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FireBase_DemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
